### PR TITLE
add explanation for algorithm

### PR DESCRIPTION
**Pull request by Po-Jen**
The first line in TODO is to write a tutorial for conveying the idea of algorithm. I want to help on this so I wrote a simple tutorial.

### CODE REVIEW

**Comment by Po-Jen** [comment]
I've found that the docs are commonly written in reStructuredText, should I use reStructuredText instead of Markdown?

**Comment by vrabaud** [comment]
yes, I was actually preparing the repo for you. Ideally ,The index.rst should point to your file

**Comment by Po-Jen** [comment]
Thanks, I guess when the repo is ready, I'll need to
 
    git remote add ork https://github.com/wg-perception/transparent_objects.git (because I wasn't familiar with the git work flow, so I've modified my master branch. It's a little bit awkward now)
    git branch tutorial_rst (this branch is at a5cea8e - clean extensions)
    git checkout tutorial_rst
    git fetch ork master
    git merge ork/master (update to the prepared repo)
    add algorithm.rst in a folder
    edit doc/source/index.rst to reference algorithm.rst (so http://wg-perception.github.io/transparent_objects/ will update itself)
    git push 
    open a new PR

Have I missed something?

**Comment by vrabaud** [comment]
ok, code is clean here: https://github.com/wg-perception/transparent_objects/commit/bfd1d43a5a123c01df23a8d230cd5c31ed31e204

You can work on master. What you did is good. All you need to do is ```git pull --rebase```, update your commits and push. This merge request will be automatically updated.

**Comment by Po-Jen** [comment]
I already updated this merge request, thx~

**Comment by vrabaud** [comment]
lgtm, thx ! The doc should be updated online at http://wg-perception.github.io/transparent_objects/index.html

**Pull request merged**
